In [1]:
import numpy as np

In [3]:
a = np.array([[0, 1, 1], [1, 0, 0], [1, 0, 0]])
w, v = np.linalg.eig(a)
print(w)
print('')
print(v)

[ 1.41421356 -1.41421356  0.        ]

[[ 7.07106781e-01  7.07106781e-01  1.54074396e-33]
 [ 5.00000000e-01 -5.00000000e-01 -7.07106781e-01]
 [ 5.00000000e-01 -5.00000000e-01  7.07106781e-01]]
